### PR TITLE
Refactor/modularize components & add tests.

### PR DESCRIPTION
**Pull request by jpetto**
Refactors components to be more modular/easily tested & adds tests.

### CODE REVIEW

**Comment by jpetto** [comment]
@glogiotatidis - As this is my first pass at writing React/Redux tests (and using Jest), don't hesitate to tell me if these tests are sloppy nonsense.

Also would love to learn how to integrate these tests into CI.

**Comment by jpetto** [comment]
@glogiotatidis - No pressure, but I've got a [branch to display service details](https://github.com/jpetto/status.mozmar.org/tree/enable-service-detail-view) ready for a PR after this one lands. 😉

**Comment by glogiotatidis** [comment]
I see that tests run (and pass) with `npm test` on Travis. Locally i installed Jest and i get the following errors

```
 PASS  src/__tests__/actionCreators.test.js
 PASS  src/__tests__/reducers/global.test.js
 PASS  src/__tests__/helpers.test.js
 FAIL  src/__tests__/ServiceSummary.test.js
  ● Test suite failed to run

    Cannot find module 'object-assign' from 'ReactTestRenderer.js'
      
      at Resolver.resolveModule (node_modules/react-scripts/node_modules/jest-resolve/build/index.js:144:17)
      at Object.<anonymous> (node_modules/react-test-renderer/lib/ReactTestRenderer.js:15:15)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:3:18)

 FAIL  src/__tests__/GlobalStatus.test.js
  ● Test suite failed to run

    Cannot find module 'object-assign' from 'ReactTestRenderer.js'
      
      at Resolver.resolveModule (node_modules/react-scripts/node_modules/jest-resolve/build/index.js:144:17)
      at Object.<anonymous> (node_modules/react-test-renderer/lib/ReactTestRenderer.js:15:15)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:3:18)

Test Suites: 2 failed, 3 passed, 5 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        1.011s
Ran all test suites.
```

**Comment by glogiotatidis** [comment]
Besides the test error, this lgtm @jpetto. Eager to see the other PR. Thanks and happy 🆕 year!

**Comment by jpetto** [comment]
Hm, odd that it's not finding that dependency. Try wiping out `/node-modules` locally and re-running `npm install`. If that doesn't work, check your local version of npm? I'm on 3.3.12.

**Comment by glogiotatidis** [comment]
Re-installed everything and works fine

**Pull request merged**
